config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :meetings, except: %i[new show]
  resources :comments, only: %i[create destroy]
  root 'home#index'
  get '/index' => 'home#index', as: :index
  get '/introduction' => 'home#introduction', as: :introduction
  get '/about' => 'home#about', as: :about
  get '/joinus' => 'home#joinus', as: :joinus
  get '/staff' => 'home#staff', as: :staff
  get '/schedule' => 'meetings#index', as: :schedule
  get '/history' => 'home#history', as: :history
  get '/voice' => 'home#voice', as: :voice
  get '/rules' => 'home#rules', as: :rules
  get '/links' => 'home#external_links', as: :external_links
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  meeting_id  :integer
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  validates :description, presence: true
end

app/models/meeting.rb
# encoding: utf-8

# == Schema Information
#
# Table name: meetings
#
#  id          :integer          not null, primary key
#  start_date  :datetime
#  description :text
#  category    :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  end_at      :datetime
#

class Meeting < ApplicationRecord
  has_many :comments, -> { order(:created_at) }, dependent: :destroy
  has_many :users, through: :comments

  validates :start_date, presence: true
  validates :end_at, presence: true
  validates :category, presence: true
  validates :description, allow_nil: true, length: { maximum: 1024 }
  validate :start_date_must_before_end_at

  before_validation :format_end_at

  # scopes
  scope :future_meetings, -> { where('start_date >= ?', Time.zone.now.midnight) }

  private
  # custom validations
  def start_date_must_before_end_at
    if !start_date.is_a?(Time) || !end_at.is_a?(Time) || end_at <= start_date
      errors.add(:end_at, '時刻を正しく設定してください')
    end
  end

  # callbacks
  def format_end_at
    return if !start_date.is_a?(Time) || !end_at.is_a?(Time)
    end_at_time = end_at - end_at.midnight
    self.end_at = start_date.midnight + end_at_time
    self.end_at += 1.day if start_date >= end_at
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string
#  uid                    :string
#  username               :string           not null
#  admin                  :boolean          default(FALSE)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable,
         omniauth_providers: [:twitter]

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth['provider'], uid: auth['uid']) do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.username = auth['info']['nickname']
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  has_many :comments, dependent: :destroy

  # custom validation
  validates :username, presence: true, length: { in: 1..15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    if comment_user_equal_to_current? && @comment.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_to meetings_path
    else
      flash.now[:danger] = @comment.errors.full_messages
      session[:comment_description] = @comment.description
      redirect_to meetings_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :user_id, :meeting_id)
  end

  def comment_user_equal_to_current?
    current_user.id == comment_params[:user_id].to_i
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @future_meetings = Meeting.future_meetings.order(:start_date).take(2)
    @next_meeting = @future_meetings[0]
    @after_next_meeting = @future_meetings[1] if @future_meetings[1]
    @meeting = Meeting.new
  end

  def introduction; end

  def about; end

  def joinus; end

  def staff; end

  def history; end

  def voice; end

  def rules; end

  def external_links; end

end

app/controllers/meetings_controller.rb
# encoding: utf-8

class MeetingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :user_admin, except: [:index]

  def index
    @comment = Comment.new
    @meetings = Meeting.order(start_date: :desc).includes(:comments).includes(:users).page params[:page]
  end

  def create
    @meeting = Meeting.new(meeting_params)
    cookies[:meeting_category] = @meeting.category
    cookies[:meeting_description] = @meeting.description
    if @meeting.save
      redirect_to root_path, flash: { success: '予定を作成しました。' }
    else
      flash.now[:danger] = @meeting.errors.full_messages
      redirect_to root_url, flash: { danger: @meeting.errors.full_messages }
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting && @meeting.update_attributes(meeting_params)
      flash[:success] = 'スケジュールを更新しました。'
      redirect_to meetings_path
    else
      flash.now[:danger] = @meeting.errors.full_messages
      render :edit
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if @meeting.destroy
      redirect_to meetings_path, flash: { success: '予定を削除しました。' }
    else
      flash[:danger] = @meeting.errors.full_messages
      redirect_to root_url
    end
  end

  private

  def user_admin
    unless current_user.try(:admin?)
      redirect_back(fallback_location: root_url)
      flash[:danger] = 'you are not authenticated!'
    end
  end

  def meeting_params
    params.require(:meeting).permit(:start_date, :end_at, :description, :category)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'].except('extra'))
    if @user.persisted?
      sign_in_and_redirect @user
    else
      session['devise.user_attributes'] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/about.html.slim
- provide :title, t('application.titles.about')
article.about__questions
  h2.about__questions--title #{t('application.titles.about')}
  section.about__question
    h3.about__question--title 「ステップ」って何？
    p.about__question--anwser
      |ひきこもりの当事者・経験者による、親睦と交流のためのサークルです。
      |月に1回程度、神奈川県内で会合を開いています。
  section.about__question
    h3.about__question--title どのような活動をしているの？
    p.about__question--anwser
      |月に1回程度（土日のいずれか）、主に横浜市内の公共施設の部屋を借りて会合を開いています。
    |会合の内容はいまのところ、日ごろの悩みなどを話し合ったり、そのほかにはテーマトークや雑談、情報交換といったところで、そんな堅苦しいものではなく、おしゃべりの会に近い感じです。
  section.about__question
    h3.about__question--title 参加対象は？
    p.about__question--anwser
      |ひきこもりの当事者、またはかつてひきこもった経験があり理解のできる方を対象としています。
    |「自分がひきこもりに当てはまるのかどうかよくわからないのですが…」といった問い合わせを受けることもあるのですが、このHPの内容を読んで、何となくしっくり来るなと思われた方なら馴染めるのではないかと思います。
  section.about__question
    h3.about__question--title 会費は？
    p.about__question--anwser
      |現在、無料で借りられる施設を利用しているため、参加費は集めていません。
  section.about__question
    h3.about__question--title 会合に参加するには？
    p.about__question--anwser
      |「参加方法」のページに書いてある内容をよくお読みの上、メールを送ってください。折り返し場所等の詳細をお知らせします。
      |またその際、出来たらご自分のひきこもりについての経緯やいまの状態について、簡単に書いてくださると助かります。
  section.about__question
    h3.about__question--title 会合の参加にあたって
    p.about__question--anwser
      |参加者を把握する都合上、「参加方法」のページを参照の上、事前にメールをくださるようにお願いします。
      |会合の時間内であれば、何時に来て何時に帰っても自由です。
      |ご自分の都合や調子に合わせて、お好きな時間に参加してください。
      |会合への出席・欠席ももちろん自由です。
      |また、このサークルは精神的に若干ナイーヴなところを抱えた人たちの集まりですので、もし著しく他の参加者を傷つけたり、迷惑となる発言や行為をする方がいた場合には、退会の処置をとる場合もあります。ご了承ください。
      |尚、「ステップ」はいわゆる"オフ会"ではありませんので、ハンドル名での参加はご遠慮いただいております。
  section.about__question
    h3.about__question--title 参加者はどんな人？
    p.about__question--anwser
      |ひきこもりの当事者だけでなく、以前そうだったという「経験者」の人もいます。
      |年齢でいえば10代後半から50代後半まで、特に仕事をしていないという人から、アルバイトをしている人、通信制の学校に通っている人、他の自助グループや（スタッフのいる）デイケアに通っている人、定職に就いているけど人間関係で苦労している人、対人不安のためにひきこもりがちになっている人など、さまざまです。
      |やはり神奈川に住んでいる方の参加が多いですが、神奈川限定ということではないですし、千葉・東京・埼玉などの周辺都県の方も参加しています。
  section.about__question
    h3.about__question--title 参加者の人たちは、どういった目的で参加しているの？
    p.about__question--anwser
      |「近場でこういった場所をつくりたい」「ひきこもりに関するまじめな話がしたい」「他の人の経験談を聞いて自分の参考にしたい」「同じような悩みを抱えた仲間（友達）をつくりたい」など、人それぞれです。
  section.about__question
    h3.about__question--title （ひきこもり当事者を持つ）ご家族の方々へ
    p.about__question--anwser
      |ご家族・知人等の参加は、現在のところご遠慮いただいております。
      |また、ご家族らによる強制ではなく、あくまでもご本人の自発的な意思での参加を希望しています。
  section.about__question
    h3.about__question--title その他わからないこと
    p.about__question--anwser
      |メールにてお問い合わせください。
      = mail_to "stepkanayoko@yahoo.co.jp"

app/views/home/external_links.html.slim
- provide :title, t('application.titles.links')
article.external_links
  h2 #{t('application.titles.links')}
  h3 行政サービス
  .external_links__item
    = link_to "横須賀保健所ひきこもりガイド", "http://www.city.yokosuka.kanagawa.jp/3130/hikikomori/index.html"
    p.external__links__item__description
      |横須賀保健所で行っているひきこもり支援についてのページです。当事者グループ「ひだまりん」などの活動も行っています。

  h3 民間援助団体など
  .external_links__item
    = link_to "あしたの風クリニック（旧 爽風会佐々木病院）", "http://www.sofu.or.jp/"
    p.external__links__item__description
      |千葉県船橋市にある完全開放型の精神科病院です。社会的ひきこもりを積極的に扱い、入院・デイケアなどもやっています。

  .external__links__item
    = link_to "不登校情報センター", "http://www.futoko.info/"
    p.external__links__item__description
      |不登校やひきこもりなどの支援団体です。会報『Hiki Com'i』の発行や、サークル「人生模索の会」などを主催しています。

  .external__links__item
    = link_to "文庫こころのクリニック", "http://bunkokokoro.com/"
    p.external__links__items__description 金沢文庫にある、精神科医によるカウンセリング専門の相談室です。

  .external__links__item
    = link_to "アンガージュマン・よこすか", "http://npoey.com/"
    p.external__links__items__description
      |不登校、ひきこもりのご本人、周囲の方々と共に社会参加（=engagement)を目指しているNPO法人です。
      |ほかに不登校やひきこもりの家族会「ウィル」「未来」、父親の会「DAD」、月に一度の夜食会などもやっています。

  .external__links__item
    = link_to "NPO法人 リロード", "http://reroad.jp/"
    p.external__links__items__description
      |フリースクール楠の木学園と神奈川県の協働で活動をしている団体です。
      |ひきこもりに限らず、広く生きづらさを抱えている人たちのための居場所作りの活動をしています。
  .external__links__item
    = link_to "新ひきこもりについて考える会", "https://hkangaerukai.wordpress.com/"
    p.external__links__items__description
      |東京で活動している、当事者・家族・支援者等の三者が集まっているグループ。毎回テーマを決めて話し合いや意見交換をしています。

  h3 個人のページ
  .external__links__item
    = link_to "うつ病治療のウソ・ホント | 現役カウンセラーが教えるＱ＆Ａ専門サイト", "http://www.utu-kaiketu.jp/"
    p.external__links__items__description うつ病治療についてカウンセラーの視点から質問を解決しているサイトです。
  .external__links__item
    = link_to "話しませんか？", "http://hiki.o.oo7.jp/"
    p.external__links__items__description
      |ひきこもり、不登校、いじめの被害、対人恐怖や強迫神経症などに悩む方などのための交流の場所です。ひきこもりや相談機関についての情報が豊富です。

  .external__links__item
    = link_to "ひきこもりピアサポートとリカバリーの部屋", "https://hikikomori-peersupport.jimdo.com/"
    p.external__links__items__description
      |Stepとも交流のあるひきこもり経験者がピアサポート研究・活動をしている個人サイトです。

app/views/home/history.html.slim
- provide :title, t('application.titles.history')
article.history
  h2 #{t('application.title.ja')} #{t('application.titles.history')}
  p ステップは2015年7月で、設立されてから15年を迎えました。
  p これまでの歩みをふり返る意味でこのページを作成しました。

  h3 15周年の集い
  p
    |2015年7月には15周年の集いが行われました。
    |様々な代の参加者の交流のきっかけになればとの願いのもと、前半は皆で調理をし、色々な工程を協力し分担する中で親睦を深め、
    |後半は会合形式で、参加していた当時の話などに花を咲かせました。

  h3 ステップ年表
  .history__timeline
    .history__timeline__left
      .content
        h4 2015 - 7
        p 「15周年の集い」が開催される
    .history__timeline__right
      .content
        h4 2010 - 7
        p ステップ設立10周年を迎える
    .history__timeline__left
      .content
        h4 2009 - 11
        p 臨時のミニ会合「ミニステップ」を行う
    .history__timeline__right
      .content
        h4 2007 - 3
        p 女性限定会合「ステファニー」が始まる
        p （翌年3月まで隔月開催）
    .history__timeline__left
      .content
        h4 2005 - 8
        p 「新旧ステップ夏会合2005」が開かれる
    .history__timeline__right
      .content
        h4 2005 - 5
        p ステップの活動が再開される
    .history__timeline__left
      .content
        h4 2004 - 12
        p ステップの活動が一時休止になる
    .history__timeline__right
      .content
        h4 2000 - 7
        p ステップが設立される

app/views/home/index.html.slim
- provide :title, t('application.titles.index')

// headline information
section.headline-info
  // title logo
  .headline-info__site-logo
    h1.site-logo
      span.logo-st
        span.logo-s S
        span.logo-t T
      span.logo-ep
        span.logo-e E
        span.logo-p P
  // site description
  h2.headline-info__group-description
    |「#{t("application.title.ja")}」は、ひきこもりの当事者・経験者による、
    |親睦と交流のためのサークル・ひきこもり自助グループです。
    |現在は月に一回程度、神奈川県内で会合を開いています。

// main information
section.main-info
  .main-info__meetings-nav
    ul.nav.nav-tabs.main-info__meetings-nav__tab#meeting-tab role="tablist"
      li.nav-item
        a.nav-link.active#nextmeeting-tab data-toggle="tab" href="#nextmeeting" role="tab" aria-controls="#nextmeeting" aria-selected="true"
          |次回の予定
      li.nav-item
        a.nav-link#afternextmeeting-tab data-toggle="tab" href="#afternextmeeting" role="tab" aria-controls="#afternextmeeting" aria-selected="false"
          |次々回の予定
      li.nav-item
        = link_to "スケジュール", meetings_path, class: "nav-link", id: "meetings", "aria-selected": "false"
      - if current_user.try(:admin)
        li.nav-item
          a.nav-link#admin-menu-tab data-toggle="tab" href="#admin-menu" role="tab" aria-controls="#admin-menu" aria-selected="false"
            |管理者メニュー
    #meeting-tab-content.tab-content.main-info__meetings-nav__tab-content
      //次回の予定
      .tab-pane.fade.show.active#nextmeeting role="tabpanel" aria-labelledby="nextmeeting-tab"
        - if !!@next_meeting
          p
            | 次回の#{t('application.title.en')}は
            span.meeting__date.text-primary #{l @next_meeting.start_date, format: :full_date} 〜 #{l @next_meeting.end_at, format: :time_only}
            | に#{@next_meeting.category}を予定しています。
            .nextmeeting__description
              = simple_format(@next_meeting.description)
        - else
          p 未定です。

      //次々回の予定
      .tab-pane.fade#afternextmeeting role="tabpanel" aria-labelledby="afternextmeeting-tab"
        - if !!@after_next_meeting
          p
            |次々回は
            span.meeting__date.text-primary #{l @after_next_meeting.start_date, format: :full_date}
            |を予定しています。
        - else
          p 未定です。

      //管理者メニュー
      .tab-pane.fade#admin-menu.main-info__meetings-nav__tab-content--admin-menu role="tabpanel" aria-labelledby="admin-menu-tab"
        - if current_user.try(:admin)
            p 予定を追加する
            = render 'meetings/form'

app/views/home/voice/_al.html.slim
h2 AL さん

h3 ステップに参加していた時期
p 設立当初から1年半くらい。

h3 当時のステップの会合について
p テーマごとにグループで話合い、フリートークなどをしていた記憶があります。あまり重たい空気ではなかったと思います。

h3 当時のことで印象に残っていることや感想
p 記憶が薄れてでてきません・・・。

h3 「ステップ」が自分の人生にとってどんなステップになったか
p
  |わたしはずっといつか何かが起こって自分の生活が好転するのではないかと、そうなったらいいなと思っていました。
  |でも、そんなものはないんだということを、いい意味であきらめさせてくれたきっかけのひとつです。

h3 今現在の状況
p
  |専業主婦で子育て中。1才の子供がいます。
  |そろそろ仕事をしたいなーと思っていますがなかなか腰が上がらず。

h3 ステップが作られた経緯について
p
  |とびらの会という自助グループ内で神奈川県在住者のグループをつくろうという話が持ち上がったのがきっかけだったと思います。
  |とびらの会は主に東京で月1回会合をしていましたが、もっと会合の機会を増やしたいという方が多くステップに限らずあっちこっちに自助グループができていました。
  |スタッフはしていないので事務的な内容はわかりません。

app/views/layouts/_footer.html.slim
// footer
.footer__copyright
  small &copy; 2017 STEP All Rights Reserved.

app/views/meetings/edit.html.slim
h2 スケジュールの更新
= render 'meetings/form'

app/views/meetings/index.html.slim
- provide :title, t('application.titles.meetings')
h2 #{t('application.titles.meetings')}
.meetings-info
  - @meetings.each do |meeting|
    ul.meeting-list.list-group.my-4
      li.meeting-list__category.list-group-item.list-group-item-primary.d-inline-flex
        div
          = meeting.category
        ul.flex-row.d-none.d-md-flex.ml-md-auto
          - if user_signed_in?
            button.btn.btn-primary.mr-2 type="button" data-toggle="modal" data-target="#meeting_#{meeting.id}" Comment

            // Modal
            .modal.fade id="meeting_#{meeting.id}" tab-index="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true"
              .modal-dialog role="document"
                .modal-content
                  .modal-header
                    h5#commentModalLabel.modal-title コメント投稿
                    button.close type="button" data-dismiss="modal" aria-label="Close"
                      span aria-hidden="true" &times;
                  = form_for @comment do |f|
                    .modal-body
                      = f.hidden_field :user_id, value: current_user.id
                      = f.hidden_field :meeting_id, value: meeting.id
                      = f.text_area :description, class: "form-control"
                    .modal-footer
                      button.btn.btn-danger data-dismiss="modal" Cancel
                      = f.submit "Submit", class: "btn btn-primary"

          - if current_user.try(:admin)
            = button_to "edit", edit_meeting_path(meeting), method: :get, class: "btn btn-warning mr-2"
            = button_to "delete", meeting, method: :delete, class: "btn btn-danger"
      li.meeting-list__date.list-group-item
        span.date--label 日時：
        = l meeting.start_date, format: :full_date
        | 〜
        = l meeting.end_at, format: :time_only
      li.meeting-list__description.list-group-item
        = simple_format(meeting.description)

      // comment section
      - if meeting.comments.any?
        li.meeting-list__comments.list-group-item
          h3 コメント
          .comment-container
            - meeting.comments.each_with_index do |comment, idx|
              .comment-content
                .comment-content__idx #{idx + 1} : 
                .comment-content__author
                  span.text-info #{comment.user.username}
                  |さん
                .comment-content__created_at
                  |投稿日: #{l comment.created_at, format: :full_date}
                .comment-content__description
                  = simple_format(comment.description)

= paginate @meetings